/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myFirstGradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    private void testRandom() {
    	
    	System.out.println("HelloWorld");
        

    	System.out.println("HelloWorld 3");
    	
    	System.out.println("HelloWorld 4");
    	
    	System.out.println("HelloWorld 5");
    }
    
    private void testRebase3() {
    	
    }
    
    
    private void testRebase() {
    	System.out.println("test Rebase");
        
        System.out.println("1");
        
        System.out.println("2");
        
        System.out.println("3");
    }
    
    private void testRebase2() {
    	System.out.println("testRebase2");
    	
    	System.out.println("testRebase2 again");
    }
    
    private void testNewMethod() {
        
        System.out.println("3");
    	
    	 System.out.println("1");
    	 
    	 System.out.println("2");
    	
    }
    
    public void testAnotherRebase(){
    	System.out.println("1");
    	System.out.println("2");
        System.out.println("3");
    }
    
     public void testConflict(){
         
         System.out.println("Another conflict");
    }

    
     private void callToTestRebase() {
        testRebase();
    }  
    
    
}





