/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myFirstGradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    
    private void testRandom() {
    	
    	System.out.println("HelloWorld");
        
        
    	System.out.println("HelloWorld 3");
        
        System.out.println("HelloWorld 5");
    }
}





