/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myFirstGradle;

public class Library {

    private int a;
    /**
     * Method comment
     *
     * @return
     */
    public boolean someLibraryMethod() {
        return true;
    }

}
