/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myFirstGradle;

public class Library {
    private int b;
    private int a;
    private int c;
    private int d;
    private int e;
    private int f;
    private int g;
    public boolean someLibraryMethod() {
        return true;
    }

}
