/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myFirstGradle;

public class Library {
    private int b;
    private int a;
    public boolean someLibraryMethod() {
        return true;
    }

}
